name: Run Selenium Tests with Allure

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          npm install -g allure-commandline --save-dev

      - name: Run tests and generate Allure results
        run: |
          pytest --alluredir=allure-results

      - name: Generate Allure HTML report
        run: |
          allure generate allure-results -o allure-report --clean

      - name: Upload Allure report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-html-report
          path: allure-report
